add_rules("mode.debug", "mode.release")
target("foo")
    set_kind("static")
    add_files("src/lib/foo/*.cpp")
    add_headerfiles("src/inc/foo/*.hpp")
    add_includedirs("src/inc/foo", {public = true})
target("package_remote_origin")
    set_kind("binary")
    add_files("src/*.cpp")
